### ISSUE TITLE
Misc improvements

### ISSUE THREAD

**Issue by d2hydro** [d2hydro/wiwb#1]
- [x] refactor globals to constants
- [x] force valid values of GetGrids.epsg so geoseries can be reprojected
- [x] specify init of Api() in readme.md
- [x] docstring at GetGrids.sample() specifying typing for stats (rasterstats module)
- [x] specify typing for GetGrids.data_format_code (and docstrings)
- [x] silence pyproj warning
- [x] Auth.get_token() to internal method Auth._get_token()
- [x] Validate samples from WIWB and provided NetCDF in pytest; compare results with expected results saved in CSV
- [x] remove `__setattr__` from GetGrids, introducing `set_geometries` and `set_` for every property that needs validation when setting
- [x] `write()` -> `to_directory()`
- [x] `auth.token_valid` naar `auth.is_token_valid`
- [x]  raise FileNotFoundError if directory does not contain valid netcdfs in `sample_nc_dir`
- [x] add `sample_netcdfs()` with a file-list
- [x] join stats list to string at `sample.sample_geoseries`
- [x] update readme.md with examples `sample_nc_dir` and `to_directory()`

**Comment by d2hydro** [comment]
For avoiding a custom `__setattr__` , and making the geometry property init-only we can modify the code as (minimal example):

```
from dataclasses import dataclass, InitVar, field
from shapely.geometry import Point, Polygon, MultiPolygon
from geopandas import GeoSeries
from typing import Iterable, Union

@dataclass
class GetGrids():
    epsg: int = 28992
    geometries: InitVar[GeoSeries | Iterable[Union[Point, Polygon, MultiPolygon]]]

    _geometries: int = field(init=False,) 

    def __post_init__(self, geometries):
        self._geometries = geometries

    @property
    def geometries(self):
        return self._geometries
    
    def set_geometries(self, geometries):
        self._geometries = geometries
        return geometries
```

**Comment by ghost** [comment]
@DanielTollenaar :
Nice, thanks for fixing all these issues! I just tested the main branch, and it works! :)
Some minor last things:
1. I believe we agreed on renaming GetGrids.run() to GetGrids.download(), didnt we?
2. I think set_geometries() should return None (only set _geometries). type hint return = -> None. If you dont think so, then let it return self._geoseries instead of return self.geoseries. 
from:
````
        if geometries is not None:
            geoseries = self._to_geoseries(geometries)
            self._geoseries = geoseries
        else:
            self._geoseries = geometries
        return self.geoseries
````
to
```
        if geometries is not None:
            geoseries = self._to_geoseries(geometries)
        self._geoseries = geoseries
        return self._geoseries
```      
3. the same goes for set_bounds(), let it return None (also type hint)
4. i find this a bit confusion:
```
    grids.set_geometries(GEOSERIES)
    a = grids.geometries  # this is None
    b = grids.geoseries   # this is not None
```
Do you agree? If so, either rename set_geometries() to set_geoseries(), or try to use one of the two, or perhaps you have a better solution?

**Comment by DanielTollenaar** [comment]
> @DanielTollenaar : Nice, thanks for fixing all these issues! I just tested the main branch, and it works! :) Some minor last things:
> 
> 1. I believe we agreed on renaming GetGrids.run() to GetGrids.download(), didnt we?
> 2. I think set_geometries() should return None (only set _geometries). type hint return = -> None. If you dont think so, then let it return self._geoseries instead of return self.geoseries.
>    from:
> 
> ```
>         if geometries is not None:
>             geoseries = self._to_geoseries(geometries)
>             self._geoseries = geoseries
>         else:
>             self._geoseries = geometries
>         return self.geoseries
> ```
> 
> to
> 
> ```
>         if geometries is not None:
>             geoseries = self._to_geoseries(geometries)
>         self._geoseries = geoseries
>         return self._geoseries
> ```
> 
> 3. the same goes for set_bounds(), let it return None (also type hint)
> 4. i find this a bit confusion:
> 
> ```
>     grids.set_geometries(GEOSERIES)
>     a = grids.geometries  # this is None
>     b = grids.geoseries   # this is not None
> ```
> 
> Do you agree? If so, either rename set_geometries() to set_geoseries(), or try to use one of the two, or perhaps you have a better solution?

Regarding returns of functions; I agree, though with set_geometries you could argue you won't always get returned what you enter; geometries are converted to geoseries (GeoPandas) and reprojected if provided as geoseries (and projection is not self.epsg)

Regarding geometries vs geoseries. Agree it's confusing, however:
1. `set_geometries` accepts a list of geometries ór a geopandas.GeoSeries. Both are geometries, but both aren't geoseries
2. self.geoseries always returns a pandas.GeoSeries as the list of geometries is converted (and projected) to a geopandas.GeoSeries
3. Using the InitVar `geometries` ánd decorated property `geometries` doesn't work as grids.geometries won't  return the stored GeoSeries but other bogus. Hencewhy I use `grids.bbox` as decorated property returning `grids._bounds`.
